#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoibWFyay5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3ODY2ODAzNjMsImV4cCI6MTc4NjY4Mzk2MywiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.n3W7NRzUgPqE1xn56WSfV2HLmYA5TLzM9t72PToDczk## Create Blog Post
# @name createPost

< {%
  const currentDate = new Date().toISOString();
  client.global.set("currentIsoDate", currentDate);
%}

POST {{baseUrl}}/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoibWFyay5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3ODY3NzEzODQsImV4cCI6MTc4Njc3NDk4NCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.DgsJSYXzIKBynLaRYcVGmc13osEDiK9FB9rWLhr_9_o

{
  "title": "Scalable NestJS API Testing-2",
  "postType": "post",
  "slug": "scalable-nestjs-api-testing-2",
  "status": "draft",
  "content": "A detailed guide on setting up modular HTTP requests using kulala.nvim.",
  "schema": "{\"type\":\"article\"}",
  "featuredImageUrl": "http://example.com/images/nest.png",
  "tags": [1]
}
